arger-tao: arger-tao.c mystring.c
	gcc arger-tao.c mystring.c -o arger-tao

clean:
	rm -f arger-tao *.o

# all: arger-tao
#ifndef HEADER_FILE
#define HEADER_FILE
# TARGET =  arger-tao
# CC = gcc
# CFLAGS = -I
# DEPS = mystring.h
# OBJ = $(TARGET).o 

# %.o:%.c $(DEPS)
# 		$(CC) -c -o $@ $<
# $(TARGET): $(OBJ)
# 		$(CC) -o $@ $^

# clean:
# 	rm -f $(TARGET).o

# # The clean target is used to remove the executable and object files.
# make: arger-tao.o mystring.o
# 	$(CC) -o make arger-tao.o 
#endif


# CC = gcc
# CFLAGS = -Wall
# DEPS = primes.h
# OBJ = go.o primes.o

# %.o: %.c $(DEPS)
#         $(CC) $(CFLAGS) -c -o $@ $<

# go: $(OBJ)
#         gcc $(CFLAGS) -o $@ $^